#
# Make input plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id$
#

SUBDIRS = xing sidplay ogg mikmod sndtst sc68 spc nsf ffmpeg

#SUBDIRS +=  cdda

include ../../Makefile.inc
