# dcplaya - mikmod - driver - Makefile
#
# $Id$ 

#LIBRARY=yes
OBJS = drv_dcplaya.o drv_nos.o

KOS_LOCAL_INCS = -I. -I../../../../../include
KOS_INCS = -I../include

OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../../../Makefile.inc
