# dcplaya - mikmod - playercode - Makefile
#
# $Id$ 

#LIBRARY=yes

KOS_LOCAL_INCS = -I.
KOS_INCS = -I../include
KOS_LOCAL_CFLAGS = -Dstrcasecmp=stricmp
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../../../Makefile.inc
