# Main application Makefile for Dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard
#
# $Id$

LEZ=yes
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

TOPDIR:=$(dir $(shell pwd))

KOS_LOCAL_INCS := -I../include -I.. -I../libs
#KOS_LOCAL_CFLAGS += -DDREAMMP3_HOME="\"$(TOPDIR)dcplaya/make-cd/dcplaya\""

include ../Makefile.inc
# DO NOT DELETE
