#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id$
#

LEZ=yes

KOS_LOCAL_INCS := -I. -I../../../include
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../Makefile.inc
