# Makefile for dcplaya ta library
# 
# (c)2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id$

OPTIMIZE=$(OPTIMIZE_FOR_SPEED)
LIBRARY=yes
KOS_LOCAL_INCS = -I.. -I../../include
KOS_LOCAL_CFLAGS =

include ../../Makefile.inc
